run:
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - depguard
    - dogsled
    - dupl
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - govet
    - interfacer
    - misspell
    - nolintlint
    - scopelint
    - typecheck
    - unconvert
    - unparam
    - whitespace
