env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - id: "upx"
    env:
      - CGO_ENABLED=0
    binary: upx
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  - id: default
    builds:
      - upx
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"

brews:
  - goarm: 6
    tap:
      owner: huangnauh
      name: homebrew-tap
    commit_author:
      name: "huangnauh"
      email: "huanglibo2010@gmail.com"
    description: "UPYUN Storage Command Tool"

publishers:
  - name: upyun
    checksum: true
    cmd: ../upx put {{ .ArtifactName }} /softwares/upx/
    dir: "{{ dir .ArtifactPath }}"
    env:
      - HOME={{ .Env.HOME }}
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
