name: Build
on:
  pull_request:
  push:
    tags-ignore:
      - '*.*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [^1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Go modules
        run: go mod download

      - name: Build
        run: |
          go build -v .
          ./upx -v
      - name: Install
        run: |
          go get -u github.com/upyun/upx
          upx -v
